version: "3"

services:
	nodejs:
		build:
			context: .
		image: nodejs:12.16-alpine
		container_name: nodejs
		env_file: .env
		ports:
			- "3000:3000"
		environment:
			- MONGO_USERNAME=$MONGO_USERNAME
			- MONGO_PASSWORD=$MONGO_PASSWORD
			- MONGO_HOSTNAME=db
			- MONGO_PORT=$MONGO_PORT
			- MONGO_DB=$MONGO_DB
		volumes:
			- .:/home/node/app
			- node_modules:/home/node/app/node_modules
		networks:
			- app-network
		command: ./wait-for.sh db:27017 -- node server.js
	db:
		image: mongo:4.1.8-xenial
		container_name: db
		env_file: .env
		build:
			dockerfile: Dockerfile_m
			context: .
		environment:
			- MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
			- MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
		volumes:
			- dbdata:/data/db
		networks:
			- app-network
networks:
	app-network:
		driver: bridge

volumes:
	dbdata:
	node_modules:
